Blog/urls.py
from django.urls import path
from . import views

app_name="Blog"

urlpatterns = [
    path('index/',views.home_page,name='home'),
    path('detail/<id>/',views.blog_detail_view,name="detail"),
    path('create/',views.create_view,name='create'),
    path('update/<id>/',views.update_view,name='update'),
    path('delete/<id>/',views.delete_view,name='delete'),
    path('like/<id>/',views.like_blog,name='like_blog'),
     
]

accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"

urlpatterns = [
    path("login/",views.login_view,name="login"),
    path("register/", views.register_view, name="register"),
    path("logout/", views.logout_view, name="logout"),
    path("activation/<uuid64>/<token>/", views.activation_view, name="activation"),
]

core/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Blog.urls')),
    path('',include('accounts.urls')),
]


from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Blog/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User

# Create your models here.
class AbstractModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True
        


class Blog(AbstractModel):
    name = models.CharField(max_length=255)
    description = RichTextField(blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, related_name='liked_blogs', blank=True)

    def __str__(self):
        return self.name
      
      
def upload_image(instance, filename):
    name = instance.blog.name.lower().replace(' ', '-')
    return f"products/{name}/{filename}"
  

class BlogImage(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=upload_image)

    def __str__(self):
        return self.blog.name

accounts/models.py
from django.db import models

# Create your models here.

Blog/forms.py
from django import forms
from .models import Blog

class BlogForm(forms.ModelForm):
  class Meta:
    model = Blog
    
    fields = "__all__"
    

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model, authenticate


User = get_user_model()


class FormControl(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({"class": "form-control"})



class LoginForm(forms.ModelForm, FormControl):
    username = forms.CharField()


    class Meta:
        model = User
        fields = ("password", )
    
    
    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        
        user = authenticate(username=username, password=password)
        
        if not user:
            raise forms.ValidationError("This user does not exist")
        
        if not user.is_active:
            raise forms.ValidationError("This account is not activated")
        
        return super().clean()




class RegisterForm(forms.ModelForm, FormControl):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ("username", "password", "email", "first_name", "last_name")


    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")

        if len(password) < 6:
            raise forms.ValidationError("Passwordun minimum uzunlugu 6 olmalidir")

        if not password[0].isalpha() and not password[0].isupper():
            raise forms.ValidationError("Password boyuk herfle baslamalidir")
        
        return super().clean()


    def save(self, commit=True):
        password = self.cleaned_data.pop("password")
        self.cleaned_data["is_active"] = False

        if commit:
            user = User.objects.create(**self.cleaned_data)
            user.set_password(password)
            user.save()
            return user

        user = User(**self.cleaned_data)
        user.set_password(password)
        return user

Blog/views.py
from django.shortcuts import render, redirect,get_object_or_404
from .models import Blog
from .forms import BlogForm
from django.contrib.auth.decorators import login_required

# Create your views here.

def home_page(request):
  blogs = Blog.objects.all()

  context = {
    "blogs":blogs,
  }
  return render(request,"index.html",context)


def blog_detail_view(request,id):
   blog = get_object_or_404(Blog, id=id)
   
   
   context = {
      'blog': blog,
    }
    
  
   return render(request, "detail.html",context)


@login_required
def create_view(request):
    form = BlogForm()

    if request.method == 'POST':
        form = BlogForm(request.POST, request.FILES)
        if form.is_valid():
            blog = form.save(commit=False)
            blog.user = request.user
            blog.save()
            return redirect('Blog:home')  
    
    context={
      "form":form
    }

    return render(request, 'create.html', context)
  
def update_view(request,id):
  # blog = Blog.objects.get( id=id) 
  blog = get_object_or_404(Blog,id=id)
  form = BlogForm(instance=blog)
  if request.method == 'POST':
    form = BlogForm(request.POST,instance=blog)
    
    if form.is_valid():
      form.save()
      
      return redirect ("Blog:home")
  
  context={
      "form":form
    }
  return render(request, "update.html",context)



def delete_view(request, id):
    blog = get_object_or_404(Blog, id=id)

    if request.method == 'POST':
        blog.delete()
        return redirect("Blog:home")
        
    context = {
        "blog": blog
    }
    return render(request, "delete.html", context)
  
  
@login_required
def like_blog(request, id):
    blog = get_object_or_404(Blog, id=id)
    if request.user in blog.likes.all():
        blog.likes.remove(request.user)
    else:
        blog.likes.add(request.user)
    return redirect('Blog:home')  

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model, login, logout
from .forms import LoginForm, RegisterForm
from django.core.mail import send_mail
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.utils.encoding import smart_str, smart_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib import messages
from django.conf import settings
from .decorators import check_user_login


User = get_user_model()


@check_user_login
def login_view(request):
    form = LoginForm()
    print("GET request: ", request.GET)
    next = request.GET.get("next")

    if request.method == "POST":
        form = LoginForm(request.POST or None)

        if form.is_valid():
            username = form.cleaned_data.get("username")
            user = User.objects.get(username=username)

            login(request, user)


            if next:
                return redirect(next)
            return redirect("Blog:home")

    context = {
        "form": form
    }
    return render(request, "accounts/login.html", context)



def register_view(request):
    form = RegisterForm()

    if request.method == "POST":
        form = RegisterForm(request.POST or None)
        if form.is_valid():
            user = form.save()

            
            token = PasswordResetTokenGenerator().make_token(user)
            uuid64 = urlsafe_base64_encode(smart_bytes(user.id))
            link = f"http://localhost:8000/accounts/activation/{uuid64}/{token}/"

           
            send_mail(
                "Activation",
                f"Please click the link below\n{link}",  
                settings.EMAIL_HOST_USER,
                [user.email],
                fail_silently=False
            )

            return redirect("Blog:home")

    context = {
        "form": form
    }
    return render(request, "accounts/login.html", context)



def logout_view(request):
    logout(request)
    return redirect("/")



def activation_view(request, uuid64, token):
    id = smart_str(urlsafe_base64_decode(uuid64))
    user = User.objects.get(id=id)

    if not PasswordResetTokenGenerator().check_token(user, token):
        message = "Link Duzgun Deyil"
        messages.error(request, message)
        return redirect("accounts:login")

    user.is_active = True
    user.save()

    login(request, user)
    return redirect("Blog:home")

templates/accounts/login.html
{% extends "base.html" %} {% load static %} {% block css %}
<link rel="stylesheet" href="/static/style.css" />
{% endblock %} {% block body %}
<div class="container">
  <form class="w-50" method="POST">
    {% csrf_token %}
    <div >
      {% if messages %} {% for message in messages %}
      <div class="alert alert-danger" role="alert">{{ message|escape }}</div>
      {% endfor %} {% endif %} {% if form.errors %}
      <div class="error-message mb-4">
        {% for field in form %} {% for error in field.errors %}
        <div class="alert alert-danger" role="alert">{{ error|escape }}</div>
        {% endfor %} {% endfor %} {% for error in form.non_field_errors %}
        <div class="alert alert-danger" role="alert">{{ error|escape }}</div>
        {% endfor %}
      </div>
      {% endif %}
    </div>

    {% for field in form %}
    <p >
      <label>{{ field.label }}</label>
      <br />
      {{ field }}
    </p>
    {% endfor %} {{form.media}}

    <button class="submit">Submit</button>
  </form>
</div>
{% endblock %}

templates/base.html
{% load static %} 
{% block css %}
<link rel="stylesheet" href="/static/style.css" />
{% endblock %}
{% include 'header.html' %}



{% block body %}
  
{% endblock body %}

{% include 'footer.html' %}
  

templates/create.html
{% extends 'base.html' %} {% load static %} {% block css %}
<link rel="stylesheet" href="/static/style.css" />
{% endblock %} {% block body %}
<div class="container">
  <h2>Create Blog</h2>

  {% comment %}
  <form method="POST">
    {% csrf_token %} {{ form.as_p }}
    <input type="submit" value="Save" />
  </form>
  {% endcomment %}
  <div class="create_form">
    <form method="POST">
      {% csrf_token %}
      <p>{{ form.name.label_tag }} {{ form.name }}</p>
      <p>{{form.description.label_tag }} {{ form.description }}</p>
      <p>{{ form.image.label_tag}} {{ form.image }}</p>

      <input class="submit" type="submit" value="Save" />
    </form>
  </div>
</div>
{% endblock body %}

templates/delete.html
{% extends 'base.html' %}{% load static %} 
{% block css %}
<link rel="stylesheet" href="/static/style.css" />
{% endblock %} {% block body %}

<h2>Delete Blog</h2>
<p>Are you sure you want to delete the blog "{{ blog.name }}"?</p>
<form method="POST">
  {% csrf_token %}
  <input class="submit" type="submit" value="Delete" />
</form>
{% endblock body %}

templates/detail.html
{% extends "base.html" %}{% load static %} {% block css %}
<link rel="stylesheet" href="/static/style.css" />
{% endblock %} {% block body%}

<div class="container" style="height: 35vh">
  <h1 style="padding-bottom: 8px; text-align: center">
    Detail information about Blog
  </h1>
<div style="font-size: 24px; color: #fff;padding-bottom:8px">

  <h3>{{ blog.name }}</h3>
</div>
  
  <p style="font-size: 18px;padding-bottom:8px">{{ blog.description }}</p>
  <img src="{{ blog.image.url }}" width="300" height="300" />
</div>
{% endblock%}

templates/footer.html
<footer>
  <div class="footer">
    <div class="container">
      <div class="footer-flex">
        <div class="footer-section">
          <div class="footer-logo">
            <a href="#"
              ><img
                src="https://preview.colorlib.com/theme/tralive/assets/img/logo/logo2_footer.png"
                alt=""
            /></a>
          </div>
          <p>
            Land behold it created good saw after she'd Our set living.
            Signs midst dominion creepeth morning laboris nisi ufsit
            aliquip.
          </p>
          <div class="footer-icon">
            <a href="#"><i class="fa-brands fa-twitter"></i></a>
            <a href="#"><i class="fa-brands fa-facebook-f"></i></a>
            <a href="#"><i class="fa-brands fa-linkedin-in"></i></a>
            <a href="#"><i class="fa-brands fa-pinterest-p"></i></a>
          </div>
        </div>

        <div class="footer-section">
          <h4>Navigation</h4>
          <ul>
            <li><a href="#">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Services</a></li>
            <li><a href="#">Blog</a></li>
            <li><a href="#">Contact</a></li>
          </ul>
        </div>
        <div class="footer-section">
          <h4>Services</h4>
          <ul>
            <li><a href="#">Blackforest</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Services</a></li>
            <li><a href="#">Blog</a></li>
            <li><a href="#"></a></li>
          </ul>
        </div>

        <div class="footer-section">
          <h4>Contact Us</h4>
          <p>76/A, Green Lane, Dhanmondi, NYC</p>
          <p>demomail89@gmail.com</p>
          <h2><a href="#">+10 (78) 738-9083</a></h2>
        </div>
      </div>

      <div class="copy">
        <div class="copy-text">
          <p>
            Copyright ©2022 All rights reserved | This template is made with
            <i class="fa-solid fa-heart"></i> by <a href="#"> Colorlib</a>
          </p>
        </div>
      </div>
    </div>
  </div>
</footer>
</body>
</html>

templates/header.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <div class="main-container">
      <div class="header">
        <header>
          <div class="container">
            <a class="navbar-brand" href="#">
              {% if request.user.is_authenticated %} {{ request.user.username }}
              {% else %}
              <img
                src="https://preview.colorlib.com/theme/karma/img/logo.png"
                alt=""
              />
              {% endif %}
            </a>

            <div class="navbar">
              <ul class="nav-item">
                <li><a href="{% url 'Blog:home' %}">Home</a></li>

                <li class="has_dropdown">
                  <a href="#">Blog</a>
                  <ul class="dropdown">
                    <li><a href="{% url 'Blog:create' %}">Create</a></li>
                    
                  </ul>
                </li>
                <li class="has_dropdown">
                  <a href="#">Pages</a>
                  <ul class="dropdown">
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    <li>
                      <a href="{% url 'accounts:register' %}">Register</a>
                    </li>
                    <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                  </ul>
                </li>
                <li><a href="#">Contact</a></li>
              </ul>

              <ul class="last-icon">
                <li>
                  <a href="#"><i class="fa-solid fa-basket-shopping"></i></a>
                </li>
                <li>
                  <a href="#"><i class="fa-solid fa-magnifying-glass"></i></a>
                </li>
              </ul>
            </div>
          </div>
        </header>
      </div>
    </div>
  </body>
</html>

templates/index.html
{% extends 'base.html' %}{% load static %} {% block css %}
<link rel="stylesheet" href="/static/style.css" />
{% endblock %} {% block body %}
<div class="container">
  <h2 style="padding-bottom: 8px;text-align:center">Blog List</h2>
  {% for blog in blogs %}
  <div style="height: 35vh">
    <a
      href="{% url 'Blog:detail' blog.id %}"
      style="font-size: 24px; color: #fff"
      >{{ blog.name }}</a
    >
    <p>{{ blog.description|safe|truncatechars:50  }}</p>
    {% if request.user in blog.likes.all %}
    <button class="like">
      <a href="{% url 'Blog:like_blog' blog.id %}">Unlike</a>
    </button>
    {% else %}
    <button class="like">
      <a href="{% url 'Blog:like_blog' blog.id %}">Like</a>
    </button>
    {% endif %}
    
  </div>
  {% endfor %} 
</div>
{% endblock body %}

templates/update.html
{% extends 'base.html' %}
{% load static %} 
{% block css %}
<link rel="stylesheet" href="/static/style.css" />
{% endblock %}

{% block body %}
  
<h2>Update Blog</h2>
  <form method="POST" >
    {% csrf_token %}
    
    <p>{{ form.name.label_tag }} {{ form.name }} </p>
    <p>{{form.description.label_tag }} {{ form.description }} </p>
    <p>{{ form.image.label_tag}} {{ form.image }}</p>
    <input class="submit" type="submit" value="Save">
  </form>
{% endblock body %}
  